services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations/common/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  kafka:
    image: docker.io/bitnami/kafka:3.8
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka-data:/bitnami
    ports:
      - "9092:9092"
  retryer:
    container_name: retryer
    build:
      context: .
      args:
        MAIN_PATH: ./cmd/retryer/main.go
        CONFIG_PATH: ./configs/retryer.yaml
        PIPELINE_ID: ${PIPELINE_ID}
        MODE: without_migrations
      platforms:
        - "linux/amd64"
    image: inspirate789/ds-retryer:latest
    restart: always
  gateway:
    container_name: gateway
    build:
      context: .
      args:
        MAIN_PATH: ./cmd/gateway/main.go
        CONFIG_PATH: ./configs/gateway.yaml
        PIPELINE_ID: ${PIPELINE_ID}
        MODE: without_migrations
      platforms:
        - "linux/amd64"
    image: inspirate789/ds-gateway:latest
    restart: always
    ports:
      - "8080:8080"
  cars-api:
    container_name: cars-api
    build:
      context: .
      args:
        MAIN_PATH: ./cmd/car/main.go
        CONFIG_PATH: ./configs/cars.yaml
        MIGRATIONS_FOLDER: ./migrations/car
        PIPELINE_ID: ${PIPELINE_ID}
      platforms:
        - "linux/amd64"
    image: inspirate789/ds-cars-api:latest
    restart: always
    ports:
      - "8070:8080"
  rental-api:
    container_name: rental-api
    build:
      context: .
      args:
        MAIN_PATH: ./cmd/rental/main.go
        CONFIG_PATH: ./configs/rental.yaml
        MIGRATIONS_FOLDER: ./migrations/rental
        PIPELINE_ID: ${PIPELINE_ID}
      platforms:
        - "linux/amd64"
    image: inspirate789/ds-rental-api:latest
    restart: always
    ports:
      - "8060:8080"
  payment-api:
    container_name: payment-api
    build:
      context: .
      args:
        MAIN_PATH: ./cmd/payment/main.go
        CONFIG_PATH: ./configs/payment.yaml
        MIGRATIONS_FOLDER: ./migrations/payment
        PIPELINE_ID: ${PIPELINE_ID}
      platforms:
        - "linux/amd64"
    image: inspirate789/ds-payment-api:latest
    restart: always
    ports:
      - "8050:8080"

volumes:
  db-data:
  kafka-data:
