CREATE DATABASE cars;
GRANT CREATE ON DATABASE cars TO program;

CREATE DATABASE rentals;
GRANT ALL ON DATABASE rentals TO program;

CREATE DATABASE payments;
GRANT ALL ON DATABASE payments TO program;
